services:
  api:
    build: .
    command: sh -c "uvicorn api.api:app --reload --port 3001 --host=0.0.0.0 --no-date-header"
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - .:/app
